---
title: "2023年のログと2024年の目標"
output: html_document
date: "2024-01-12"
---

# 2023年を終えて

2023年はあっという間なような、長かったようなそんな年でした。

3月より前は機械学習にはまっていました。このサイトがやや機械学習よりなのはそのせいですね(笑)。いまは、そんなに熱を入れているわけじゃないのでちょっとサイトの作り方を後悔してます。

4月から自分の将来とか人間関係を考える機会が多くなり、「未来のことなんて誰にも分らないのだから考えていても仕方ない。今できることを着実に」と考える自分と「このまま進んだ先に少しでも明るい未来はあるのか。努力次第で持ち得る可能性は変化するか」とぶつかっていました。


７月になり、大学院に内部試験で合格したので一応の進路は決まりました。もっとできることを増やしつつ、世界を広く多角的に見れる智を持ちたいという漠然とした欲はありました。しかし、指導教員だった先生に「大学院で”何をする”かは考えた方がいい」と言われ、考えていた時期でもありました。


9月から12月は卒論に時間を使いました。７月ごろからぼちぼち取り掛かっていたので、主にコードの改良や執筆でした。チャレンジとしてなるべくＲパッケージを使わずfor文で書いたので最初はなれませんでしたが、だんだん慣れてきたら楽しかったです。「私はなるべくfor文で書くんです」みたいな人の気持ちがわかりました。ディズニーランドの周り方を遺伝的アルゴリズムを用いて解くという卒業論文なので若干浮いている感は強かったですが、自分の考えたテーマを知らなかった手法で地道に研究したという経験は楽しかったです。


なんやかんや、可もなく不可もなくな一年でした。来年度からは大学院生になる(と思う)ので、また、楽しい一年を過ごせたらなと思います。

ps. 前は意気込みや感想をホームに書いていたのですが、ごちゃごちゃするので来年からは独り言に含めようと思います。以下は、2023年のホームにあったアーカイブです。

# 以下、独り言のログ

## 2023 意気込み

大学４年生になりかけていて大学生活もあっという間だなという印象を抱いています。大学をでたら就職するつもりでしたが、もう少し勉強したい思いが強くなり、先日両親に頭下げて大学院に行きたいと言いました。

今年は大学院入試を頑張りつつ、Rや統計を使って面白いことたくさんできたらいいなーと思います。気楽に楽しんでいろいろなことに挑戦し、できることを増やしたい！

## 2023 前半を終えて

卒論が思うように進まない中、大学院に受かるか不安な日々を過ごしてます。あと半年で卒論を仕上げないといけないのでやや焦り気味。大学院に受からなかったら...将来、職に就けなかったら...と不安になったらMrs. GREEN APPLEのケセラセラ聞いてます。梅雨が終われば気分も上がるでしょ！
