---
title: "RユーザーがSQLで100本ノックをやった感想"
output: html_document
date: "2024-03-21"
---

# dplyerのおかげで理解はできるが...

とある企業のインターンに申し込んだらコーディングテストにSQLが含まれていたので、初挑戦した。dplyerを長年使っていたのでデータを整理してる想像は容易にできるし、理解しやすい新しい言語を学んでいる気分で楽しかった。でも私にとってはすごくうれしかった点と気持ち悪い点があったので挙げていく。

# 嬉しかった点

## SELECTはselect関数と同じ動き

dplyerのselect関数はデータから列を指定する際に使う関数だが、SQLのSELECTも同じように使う。これはすごく親しみやすかった。かっこでくくらない点を除けばほぼ同じなのでうれしい。

(追記:GROUP BYもほぼ同じでありがたい)



# 否定が!(エクスクラメーションマーク)

一致しないものを選択するときの否定演算子が一緒なのは助かる。ほかの言語もそうかもしれないけど。

# JOINが直感的

Rだとデータを結合する場合に(私は!)繋げてからデータを選ぶのが大変なので、あらかじめ加工した2つの表を結合するようにしている。けれど、SQLではSELECTで先に必要なデータだけ選べるので便利。でも、不必要だと落としたデータに大事なものがあるかもしれないので、Rのように一つずつ考えてからデータ成型することも必要だと思う。

# へんてこりんだと思った点

## FROMはSELECTの後なの？
dplyerでは最初にデータを書き、パイプ演算子で繋げていくことが多い。なので感覚としては「データの選択→列の選択など操作→行への操作」って感じ。でも、SQLでは「列名を選択→データを選択→行への操作」になっていて気持ち悪い気がした。大きいデータから絞るイメージなんだけどまた別のイマージが必要かもしれない。

## &とか|をANDとかORと書くところ

直接英語で書けるんかい!！Rでは&とか|とかで表す演算子だけど、SQLでは英語で書いていいらしい。やや戸惑った。

## こいつ、日付を理解していやがる!

Rでも決まった形に整えたり、パッケージを使って日付を操作することも可能だけれど、SQLはデフォルトで日付のソートができる。Rだと結構文字列としてしか認識されなかったりするから面白いけどへんてこだけど便利だなと思った。


## 短いときにコードを一列で書くと変に見える

SQLを知らないときに短いSQL文を読もうとすると「SELECTとFROMをかけてデータがあって...」となっていたが、短いときは改行せずに書くのね。綺麗に開業したい気持ちもあるけど、すっきり読めるし慣習なのかな。

# できると楽しくなってきちゃった

「僕にはdplyerという心に決めた人がいるんだ。いるんだ...。」となりつつも、何も見ないでデータを絞ったりできると楽しいですね。100本ノックをやりながら、データを分析する仕事に就き、いつかSQLを使う場面が来てほしいと思いました。
